### ISSUE TITLE
Add to usual stops broken in StopsPage

### ISSUE THREAD

**Issue by helfio** [helfio/harbour-BuStopSevilla#4]

**Comment by PaskoMoto** [comment]
Hola.
Después de mucho pelear con los push y los pull github me indica que no tengo permiso para hacer push en tu repositorio :P 
Si ves que lo puedes habilitar, perfecto. Sino intentaré hacerlo sobre mi fork....
Saludos.

**Comment by helfio** [comment]
#5 soluciona esto.
